[package]
name = "conditions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rhai = { version = "1.15.0", default-features = false, features = [ "std" ] }
getrandom = { version = "0.2", features = ["js"] }
js-sys = "*"