name: Build Tester
on:
  workflow_dispatch:
    inputs:
      skip:
        description: Templates to skip
        required: false
        default: ""
      require:
        description: Templates required to run
        required: false
        default: ""

env:
  REPO: pufferpanel/pufferpanel
  VERSION: templatetester

jobs:
  build-tester:
    name: Build Template Tester
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [ "linux/amd64" ]

    steps:
      - name: Correct env
        run:
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile-templatetester
          tags: ghcr.io/${{ env.REPO }}:templatetester
          build-args: |
            sha: ${{ github.sha }}
            version: ${{ env.VERSION }}
          platforms: ${{ matrix.platform }}

  run-tester:
    name: Run Tester
    runs-on: template-tester

    needs:
      - build-tester

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run image
        run: |
          docker pull ghcr.io/${{ env.REPO }}:templatetester
          docker rm -f templatetester || true
          echo "::add-mask::${{ secrets.RUNNER_IP }}"
          docker run --rm --name templatetester --network host -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/${{ env.REPO }}:templatetester --skip "${{ inputs.skip }}" --require "${{ inputs.require }}"